dist: xenial
# Use the latest Travis images since they are more up to date than the stable release.
group: edge
sudo: false
jobs:
    include:
    
    # Run JS tests
    - language: node_js
      # The Node version here must be kept in sync with that in `package.json`.
      node_js: '12.16.1'
      cache: yarn
      before_install:
        # Try to keep version in sync with `package.json`
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.0
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn install --frozen-lockfile
      script:
        - yarn format
        - yarn build
    
    #This test helps us to check integrity of the backend code
    - language: python
      python: '3.7'
      cache: pip
      install:
        # Initialize installments 
        - pip install -r requirements.txt
      script:
        - python manage.py makemigrations
        - python manage.py migrate

    #This test helps us to check standard linting of the codebase
    - language: python
      python: '3.7'
      cache: pip
      install:
        - pip install pre-commit
      script:
        - pre-commit run --all-files

# This deploys the codebase to the Github Pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github-token
  local_dir: Frontend/build
  on:
    branch: master
